### ISSUE TITLE
为什么lable 0 是无效的？

### ISSUE THREAD

**Issue by mei123hao** [charlesCXK/SA-Gate#10]
代码中我发现在数据增强部分把所有标签都减了1，这是什么原理，可以解释一下吗？我尝试把网络改成二分类网络，标签只包含两个类别，分别是0 和 1，把类别数改成2，但是训练完成后测试并不能得到有效的输出，请问能指导一下吗？谢谢了！

**Comment by charlesCXK** [comment]
您好，NYU数据集中，标签0代表invalid area，所以将所有标签减1之后，标签255就是无效区域。这样在计算cross entropy loss的时候会比较方便。
