### ISSUE TITLE
Install apex error

### ISSUE THREAD

**Issue by small-beebee** [charlesCXK/SA-Gate#12]
作者你好！十分感谢你的开源工作，我在跑你的代码时遇到apex的安装错误，请你帮我看看！
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:354:3: error: expected ';' before 'do'
   do {                                                    \
   ^
csrc/scale_check_overflow.cpp:23:3: note: in expansion of macro 'AT_CHECK'
   AT_CHECK(grads.numel() == downscaled_grads.numel(), "Input and output grads must be the same size.");
   ^
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:355:20: warning: 'void c10::detail::deprecated_AT_CHECK()' is deprecated [-Wdeprecated-declarations]
     ::c10::detail::deprecated_AT_CHECK();                 \
                    ^
csrc/scale_check_overflow.cpp:23:3: note: in expansion of macro 'AT_CHECK'
   AT_CHECK(grads.numel() == downscaled_grads.numel(), "Input and output grads must be the same size.");
   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Device.h:5:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Allocator.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from csrc/scale_check_overflow.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:330:13: note: declared here
 inline void deprecated_AT_CHECK() {}
             ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Device.h:5:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Allocator.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from csrc/scale_check_overflow.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:355:40: warning: 'void c10::detail::deprecated_AT_CHECK()' is deprecated [-Wdeprecated-declarations]
     ::c10::detail::deprecated_AT_CHECK();                 \
                                        ^
csrc/scale_check_overflow.cpp:23:3: note: in expansion of macro 'AT_CHECK'
   AT_CHECK(grads.numel() == downscaled_grads.numel(), "Input and output grads must be the same size.");
   ^
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Device.h:5:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/c10/core/Allocator.h:6,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                 from csrc/scale_check_overflow.cpp:1:
/usr/local/lib/python3.6/dist-packages/torch/include/c10/util/Exception.h:330:13: note: declared here
 inline void deprecated_AT_CHECK() {}
             ^~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
我的编译环境
ubuntu 16.04
pytorch 1.4.0
cuda10.0
cudnn 7.6.5
gcc 7.5.0

**Comment by charlesCXK** [comment]
Hi, this version of Apex requires PyTorch==1.0.0, please downgrade the PyTorch version or install the lastest Apex from the official project page.

**Comment by small-beebee** [comment]
非常感谢你的及时回复！

**Comment by Looottch** [comment]
> Hi, this version of Apex requires PyTorch==1.0.0, please downgrade the PyTorch version or install the lastest Apex from the official project page.

Hi, did you remember requirement of cuda version? cause apex installation failed with cuda 10.0
