### ISSUE TITLE
niters_per_epoch

### ISSUE THREAD

**Issue by IzumiKUN0905** [charlesCXK/SA-Gate#15]
作者你好，感谢开源你的工作。我在复现过程中注意到niters_per_epoch的计算中还乘了(800 // C.nepochs)，请问这样做的含义是什么？

**Comment by charlesCXK** [comment]
你好，意思是这个数据集跑800遍，但我这里写的一个epoch不是遍历一个数据集一次，可能每个epoch遍历了数据集若干次

**Comment by IzumiKUN0905** [comment]
谢谢你的解答，现在我能确认我理解对了
