### ISSUE TITLE
能否提供resnet50的预训练模型？我自己下载的预训练模型权重无法对应

### ISSUE THREAD

**Issue by infinite013** [charlesCXK/SA-Gate#17]

**Comment by yangjiangeyjg** [comment]
你好，请问你最后怎么解决的呀

**Comment by infinite013** [comment]
> 你好，请问你最后怎么解决的呀

去torchseg里面下https://github.com/ycszen/TorchSeg

**Comment by yangjiangeyjg** [comment]
> > 你好，请问你最后怎么解决的呀
> 
> 去torchseg里面下https://github.com/ycszen/TorchSeg

好的，谢谢啦
