### ISSUE TITLE
数据与模型权重问题

### ISSUE THREAD

**Issue by yujack333** [charlesCXK/SA-Gate#2]
首先，感谢开源了这么好的工作。我有两个问题想请教一下作者。
1.如果我的depth image是由 depth estimation 预测出来的，且场景有室内和室外，那么我在用depth2hhade 工具的时候（https://github.com/charlesCXK/Depth2HHA-python）参数应该怎么设置。
2.请问作者可以公开你们训练好的权重吗？
十分期待您的回答，谢谢。

**Comment by charlesCXK** [comment]
您好，
1.用 depth map 生成 HHA 图像，首先需要深度图的相机参数，因为转化为 HHA 的过程中，**需要把深度图投射到 3D 点云空间**，然后计算一些属性。
其次，不同的数据集(室内、室外)需要使用不同的参数，比如 https://github.com/charlesCXK/Depth2HHA-python/blob/00b2f43f8909152d272275487ad0630b045eb66b/getHHA.py#L45 这里，会对 HHA 的三个通道的值做一些处理，让他们的值尽可能分布在 0-255 中（后面会对超出范围的值做截断，因此不处理的话很多值就无效了）。这些超参，不同的数据集的差异会比较大，比如 Cityscapes 和 NYU Depth v2 用的会很不同，但是来自同一个数据集的图，只需要使用同一套参数即可。最终生成的 HHA 图像，可以参考 NYU Depth v2 数据集中的 HHA 图像的颜色，只要合理就行。如果大量图片都很明显地呈现单一绿、红色，说明 HHA 可能有问题，因为某个通道的值普遍过大。
2.原始的权重我们没有保存，但用4块GPU可以复现我们的结果。

**Comment by yujack333** [comment]
谢谢回答，
我的理解，这里有两组参数。一组是深度相机的参数，在我的情况下是不是就是depth prediction模型训练的数据集用到的深度相机的参数？第二组参数是要对HHA的值做一个映射（目的您已经说明）。但是如果我的数据集有室内也有室外的场景，用一套超参数是否会有问题，因为我理解这一套超参数受场景的深浅的影响。还是说用室外场景的超参数就能cover到室内场景的情况？还有，两个数据集的两套超参数是怎么计算得到的呢？

**Comment by charlesCXK** [comment]
您好，
1.是的
2.室内和室外场景是不能用同一套参数的，因为室外场景的平均深度明显大于室内场景，用同一套参数会使得室内场景的 HHA 图像某个通道失去意义（值过大/过小）。NYU Depth v2数据集的超参数，是直接用的 HHA 算法提出者使用的超参。对于 Cityscapes，我是根据让 HHA 的值尽可能处于 0-255 的原则，对参数的大小进行放缩。

**Comment by yujack333** [comment]
明白了，谢谢耐心且详细的回答，点赞👍。

**Comment by zichengzichengzi** [comment]
请问如果我是按照俯视图视角在室内拍摄的话，HHA生成的超参数需要改吗，尽管HHA的的意义与原始论文不同
