### ISSUE TITLE
Pretrained Resnet101 load failed

### ISSUE THREAD

**Issue by betray12138** [charlesCXK/SA-Gate#24]
Hi author，a problem confused me that the resnet101_v1c.pth I download can't match the network size. The details are as following. Could you please tell me how to load the pretrained model into the resnet101~  Thanks
![1](https://user-images.githubusercontent.com/55013174/159412432-1453c902-bcce-4758-8359-dbcdb17cefc9.png)

**Comment by yangjiangeyjg** [comment]
Hi, how did you solve it?

**Comment by betray12138** [comment]
> Hi, how did you solve it?

Hi, you could change the default variable in DualResnet to 64 and it will make sense. The more detail you could see from the source code.
Best Wish

**Comment by yangjiangeyjg** [comment]
> > Hi, how did you solve it?
> 
> Hi, you could change the default variable in DualResnet to 64 and it will make sense. The more detail you could see from the source code. Best Wish

Thanks!
