### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by SimonVandenhende** [charlesCXK/SA-Gate#3]
Hi

Thanks for sharing the code. Is it possible to obtain the pre-trained weights for the model on NYUD-v2 for academic purposes?

Thanks.

**Comment by charlesCXK** [comment]
Hi,
Thanks for your attention. Sorry, we couldn't supply the pre-trained models in the paper because I didn't bring them out when I left the company where I was an intern. However, you could easily re-produce them with this repo and only 4 GPUs (>= 11GB each) are needed.

**Comment by SimonVandenhende** [comment]
Hi.

Thanks for the quick reply. We will train the model ourselves then. 
No worries.

**Comment by David-zaiwang** [comment]
> Hi.
> 
> Thanks for the quick reply. We will train the model ourselves then.
> No worries.

Hi, have you trained the model by yourself from scratch which achieves comparable performances?
