### ISSUE TITLE
绘图

### ISSUE THREAD

**Issue by SunXusheng5200** [charlesCXK/SA-Gate#4]
陈师兄您好，我想请教一下，论文里面神经网络的图是用什么软件绘制出来的呢？

**Comment by charlesCXK** [comment]
您好，用的是 draw.io 这个在线绘图工具，也有桌面版。

**Comment by SunXusheng5200** [comment]
多谢师兄的帮助，我的本次写作也会引用到师兄的两篇文章。以后我会持续关注您的工作。
