### ISSUE TITLE
运行错误RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Faith-Code** [charlesCXK/SA-Gate#9]
File "train.py", line 173, in <module>
    loss.backward()
  File "/home/anaconda3/envs/rgbd/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/envs/rgbd/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
作者您好，非常感谢您的开源贡献，我在调试您malleable2_5d代码的过程中出现了上述错误，有的说需要把nn.ReLU(inplace=True)中的inplace改为Flase，但是发现好像没用，请问需要怎么修改才能解决问题，非常感谢。

**Comment by charlesCXK** [comment]
您好，根据我的经验，一般导致这种情况的原因包括：
1. nn.ReLU() inplace标志 设置为了True，应该全使用False。
2. 出现了 a += b这样一个操作。需改为 a = a+b。

**Comment by ArthurZucker** [comment]
Hi, I stumbled upon the same issue, it was neither `inplace=True` nor `out += pool` but rather pytorch version. I upgraded from 1.0.0 to 1.0.1 and the error vanished. Hope this will help our peers.
